# Generated by Django 2.1.3 on 2018-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='holderName',
            field=models.CharField(blank=True, max_length=50, verbose_name='holderName'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='isNonRemitted',
            field=models.IntegerField(blank=True, verbose_name='isNonRemitted'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='ownerName',
            field=models.CharField(blank=True, max_length=50, verbose_name='ownerName'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='postalCode',
            field=models.CharField(blank=True, max_length=50, verbose_name='postalCode'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='propertyID',
            field=models.IntegerField(blank=True, verbose_name='propertyID'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='propertyTypeDescription',
            field=models.CharField(blank=True, max_length=50, verbose_name='propertyTypeDescription'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='propertyValue',
            field=models.FloatField(blank=True, verbose_name='propertyValue'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='propertyValueDescription',
            field=models.CharField(blank=True, max_length=50, verbose_name='propertyValueDescription'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='secondOwnerName',
            field=models.CharField(blank=True, max_length=50, verbose_name='secondOwnerName'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='swsPropertyID',
            field=models.IntegerField(blank=True, verbose_name='swsPropertyID'),
        ),
    ]
