# Generated by Django 2.1.3 on 2018-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20181109_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='secondOwnerName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='secondOwnerName'),
        ),
    ]
