# Generated by Django 2.1.3 on 2018-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20181109_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='swsPropertyID',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='swsPropertyID'),
        ),
    ]
