# Generated by Django 2.1.3 on 2018-11-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_dictionary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameModel',
        ),
    ]
