# Generated by Django 2.1.3 on 2018-11-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20181113_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
