# Generated by Django 2.1.3 on 2018-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_businessdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
