# Generated by Django 2.1.3 on 2018-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_lastid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='name'),
        ),
    ]
